

import React, { useState, useEffect, useRef } from 'react';
import type { Feature } from './types';
import { FEATURES, VincifyLogo, AppleIcon, PlayStoreIcon } from './constants';

// Helper components defined outside the main component to prevent re-creation on re-renders.

interface AnimateOnScrollProps {
  children: React.ReactNode;
}

const AnimateOnScroll: React.FC<AnimateOnScrollProps> = ({ children }) => {
  const [isVisible, setIsVisible] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
          observer.unobserve(entry.target);
        }
      },
      {
        rootMargin: '0px',
        threshold: 0.2 // Start animation when 20% of the element is visible
      }
    );

    const currentRef = ref.current;
    if (currentRef) {
      observer.observe(currentRef);
    }

    return () => {
      if (currentRef) {
        observer.unobserve(currentRef);
      }
    };
  }, []);

  return (
    <div ref={ref} className={`reveal-on-scroll ${isVisible ? 'is-visible' : ''}`}>
      {children}
    </div>
  );
};

interface FeatureSectionProps {
  feature: Feature;
  index: number;
}

const FeatureSection: React.FC<FeatureSectionProps> = ({ feature, index }) => {
  const isReversed = index % 2 !== 0;

  return (
    <div className="py-12 md:py-20">
      <div className={`flex flex-col md:flex-row items-center justify-center gap-10 md:gap-20`}>
        <div className={`md:w-1/2 flex justify-center ${isReversed ? 'md:order-2' : ''}`}>
          <AnimateOnScroll>
            <div className="relative w-[280px] h-[570px] md:w-[320px] md:h-[650px] bg-black/30 rounded-[40px] p-2 shadow-2xl shadow-purple-900/20 ring-1 ring-white/10 transition-transform duration-300 ease-in-out hover:scale-105">
              <img 
                src={feature.imageUrl} 
                alt={`${feature.title} screenshot`} 
                className="w-full h-full object-cover rounded-[32px]"
                loading="lazy"
              />
            </div>
          </AnimateOnScroll>
        </div>
        <div className={`md:w-1/2 text-center md:text-left ${isReversed ? 'md:order-1' : ''}`}>
          <span className="inline-block px-4 py-1 text-sm font-semibold tracking-wider text-purple-300 bg-purple-900/30 rounded-full mb-4">
            {feature.title}
          </span>
          <p className="text-xl md:text-2xl text-gray-300 leading-relaxed">
            {feature.description}
          </p>
        </div>
      </div>
    </div>
  );
};

interface StoreButtonProps {
  icon: React.ReactNode;
  storeName: string;
}

const StoreButton: React.FC<StoreButtonProps> = ({ icon, storeName }) => (
  <a href="#" className="flex items-center justify-center bg-gray-800 hover:bg-gray-700 text-white font-semibold py-3 px-6 rounded-lg transition-colors duration-300 w-full sm:w-auto transform hover:scale-105">
    {icon}
    <div>
      <span className="text-xs block text-gray-400">GET IT ON</span>
      <span className="text-lg">{storeName}</span>
    </div>
  </a>
);

// FAQ Section Components
const faqs = [
    {
      question: "What is Vincify?",
      answer: "Vincify is an AI-powered app that helps you become a modern polymath by creating personalized, bite-sized lessons on topics you want to master. Think of it as your daily to-learn list — designed to be engaging, focused, and easy to absorb in just 5 minutes a day."
    },
    {
      question: "How does it work?",
      answer: "Inside the app, you create your own daily to-learn lists — just like Da Vinci did. Add topics you're curious about, and Vincify will automatically generate bite-sized lessons using AI. Each day, the app teaches you what you’ve chosen, in a clear and focused way — no distractions, no wasted time."
    },
    {
      question: "Who is Vincify for?",
      answer: "Vincify is made for lifelong learners, busy professionals, creatives, students, and anyone who wants to grow their knowledge daily without spending hours reading articles or watching long videos."
    },
    {
      question: "Is Vincify free to use?",
      answer: "Yes, Vincify is free to install and use. For more advanced features, there will also be a premium version available."
    },
    {
      question: "What kind of lessons can I expect?",
      answer: "The lessons are personalized and generated by AI based on the topics you choose. Expect concise, thought-provoking content in fields like science, philosophy, psychology, history, and technology. They're designed to be practical, engaging, and evolve with your curiosity — one lesson at a time."
    },
    {
      question: "Can I use it on both iOS and Android?",
      answer: "Yes! Vincify will be available on both the App Store and Google Play. You’ll get the same seamless experience no matter what device you use."
    },
    {
      question: "How is this different from reading blogs or watching YouTube videos?",
      answer: "Instead of passively consuming random content, Vincify gives you focused lessons built around your goals — in a clean, distraction-free interface."
    },
    {
      question: "How is the AI trained?",
      answer: "Vincify uses state-of-the-art AI models to summarize, generate, and simplify complex topics into daily lessons. It’s designed not just to inform, but to teach in a human-centered, motivating way."
    }
];


interface FaqItemProps {
  faq: { question: string; answer: string; };
  isOpen: boolean;
  onClick: () => void;
}

const FaqItem: React.FC<FaqItemProps> = ({ faq, isOpen, onClick }) => (
    <div className="border-b border-white/10 py-6">
        <button
            className="w-full flex justify-between items-center text-left text-lg md:text-xl font-semibold text-gray-100"
            onClick={onClick}
            aria-expanded={isOpen}
        >
            <span>{faq.question}</span>
            <span className={`transform transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`}>
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M6 9L12 15L18 9" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
            </span>
        </button>
        <div className={`overflow-hidden transition-all duration-500 ease-in-out ${isOpen ? 'max-h-96 mt-4' : 'max-h-0'}`}>
            <p className="text-gray-400 leading-relaxed">
                {faq.answer}
            </p>
        </div>
    </div>
);

const FaqSection = () => {
    const [openIndex, setOpenIndex] = useState<number | null>(null);

    const handleClick = (index: number) => {
        setOpenIndex(openIndex === index ? null : index);
    };

    return (
        <section className="py-24 md:py-32">
            <div className="max-w-4xl mx-auto px-6">
                <div className="text-center mb-12">
                    <h2 className="text-3xl md:text-4xl font-bold text-white">Frequently Asked Questions</h2>
                </div>
                <div>
                    {faqs.map((faq, index) => (
                        <FaqItem
                            key={index}
                            faq={faq}
                            isOpen={openIndex === index}
                            onClick={() => handleClick(index)}
                        />
                    ))}
                </div>
            </div>
        </section>
    );
};

const MainPage: React.FC<{ setPage: (page: string) => void }> = ({ setPage }) => {
  return (
    <>
      <main className="container mx-auto px-6">
          <section className="relative py-20 md:py-32">
             <div className="absolute inset-0 z-0 overflow-hidden pointer-events-none hidden md:block">
                <img src="https://storage.googleapis.com/pai-images/17927c99738f4f9fbf49e6f2a24c7f07.png" alt="Vitruvian Man Sketch" className="absolute -left-20 -top-10 w-96 opacity-10 -rotate-12" />
                <img src="https://storage.googleapis.com/pai-images/9151c73f458145e6900f89837947701e.png" alt="Da Vinci Flying Machine Sketch" className="absolute left-1/3 top-8 w-72 opacity-5" />
                <img src="https://storage.googleapis.com/pai-images/496f30453d8641979b942d9ac9457223.png" alt="Quill and Ink" className="absolute -right-24 bottom-0 w-80 opacity-20 rotate-12" />
            </div>

            <div className="relative z-10 flex flex-col md:flex-row items-center gap-12">
              <div className="md:w-1/2 text-center md:text-left">
                <h1 className="text-5xl md:text-7xl lg:text-8xl font-bold tracking-tighter mb-4 text-gray-300 font-cinzel">
                  Vincify
                </h1>
                <p className="text-xl md:text-2xl text-gray-300 leading-relaxed mb-8">
                  The revolutionary AI-driven app that will turn you into a polymath
                </p>
                <p className="text-lg text-gray-400 mb-8">Get Vincify now on the App Store or Google Play Store</p>
                <div className="flex flex-col sm:flex-row items-center justify-center md:justify-start gap-4">
                  <StoreButton icon={<AppleIcon />} storeName="App Store" />
                  <StoreButton icon={<PlayStoreIcon />} storeName="Google Play" />
                </div>
              </div>
              <div className="md:w-1/2 flex justify-center">
                 <AnimateOnScroll>
                    <div className="relative w-[280px] h-[570px] md:w-[320px] md:h-[650px] bg-black/30 rounded-[40px] p-2 shadow-2xl shadow-purple-900/20 ring-1 ring-white/10 transform md:rotate-6 transition-transform duration-500 hover:rotate-3 hover:scale-105">
                      <img 
                        src={FEATURES[0].imageUrl} 
                        alt={`${FEATURES[0].title} screenshot`} 
                        className="w-full h-full object-cover rounded-[32px]"
                        loading="lazy"
                      />
                    </div>
                  </AnimateOnScroll>
              </div>
            </div>
          </section>

          <section className="pt-24 md:pt-32 pb-16 md:pb-24">
             <div className="max-w-5xl mx-auto px-6 text-center">
                <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">The Da Vinci Method, Reimagined</h2>
                <p className="text-lg md:text-xl text-gray-400 mb-12">
                  Leonardo da Vinci's secret to becoming a polymath was a daily to-learn list. We took his powerful habit and supercharged it with modern AI.
                </p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-left">
                  <div className="bg-white/5 p-8 rounded-2xl border border-white/10 transition-transform duration-300 hover:scale-105 hover:-translate-y-1">
                    <h3 className="text-2xl font-bold text-purple-300 mb-3">Learn with Purpose</h3>
                    <p className="text-gray-300 leading-relaxed">Instead of consuming random info, you actively build your knowledge by creating your own daily to-learn list. Vincify turns it into short, sharp, AI-powered lessons that fit into your life.</p>
                  </div>
                  <div className="bg-white/5 p-8 rounded-2xl border border-white/10 transition-transform duration-300 hover:scale-105 hover:-translate-y-1">
                    <h3 className="text-2xl font-bold text-indigo-300 mb-3">AI-Powered Genius</h3>
                    <p className="text-gray-300 leading-relaxed">Imagine if Da Vinci had a smart assistant. That's Vincify. Get the focus of a genius with the power of modern AI to turn curiosity into deep understanding, effortlessly.</p>
                  </div>
                </div>
             </div>
          </section>
          
          <section className="pt-16 md:pt-24 pb-24 md:pb-32">
            <div className="max-w-5xl mx-auto px-6">
              <div className="text-center">
                  <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Stop Drowning in Content</h2>
                  <p className="text-lg text-gray-400">In today's world, it's easy to get lost.</p>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mt-12">
                <div className="flex items-center gap-6 bg-gray-900/50 p-6 rounded-2xl border border-white/10 transition-transform duration-300 hover:scale-105 hover:-translate-y-1">
                  <span className="text-4xl">📌</span>
                  <p className="text-lg text-gray-300">Endless saved articles you never revisit</p>
                </div>
                <div className="flex items-center gap-6 bg-gray-900/50 p-6 rounded-2xl border border-white/10 transition-transform duration-300 hover:scale-105 hover:-translate-y-1">
                  <span className="text-4xl">😵‍💫</span>
                  <p className="text-lg text-gray-300">YouTube rabbit holes that waste hours</p>
                </div>
                <div className="flex items-center gap-6 bg-gray-900/50 p-6 rounded-2xl border border-white/10 transition-transform duration-300 hover:scale-105 hover:-translate-y-1">
                  <span className="text-4xl">📚</span>
                  <p className="text-lg text-gray-300">Courses you abandon halfway</p>
                </div>
              </div>
              
              <div className="text-center mt-16">
                <p className="text-2xl md:text-3xl font-bold text-white mb-4 bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-indigo-400">Vincify flips the script.</p>
                <p className="text-lg text-gray-300 max-w-2xl mx-auto">
                  We help you learn with purpose, not pressure. No fluff, no overwhelm.
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-12 max-w-4xl mx-auto">
                  <div className="flex items-center gap-6 bg-gray-900/50 p-6 rounded-2xl border border-white/10 transition-transform duration-300 hover:scale-105 hover:-translate-y-1">
                      <span className="text-4xl">🎯</span>
                      <p className="text-lg text-gray-300">Whether it's philosophy, psychology, or quantum physics — you’ll learn with intention.</p>
                  </div>
                  <div className="flex items-center gap-6 bg-gray-900/50 p-6 rounded-2xl border border-white/10 transition-transform duration-300 hover:scale-105 hover:-translate-y-1">
                      <span className="text-4xl">🕔</span>
                      <p className="text-lg text-gray-300">Just 5 focused minutes a day to become the smartest version of yourself.</p>
                  </div>
              </div>

            </div>
          </section>

          <section>
            {FEATURES.map((feature, index) => (
              <FeatureSection key={index} feature={feature} index={index} />
            ))}
          </section>
          
          <FaqSection />

          <section className="py-20 text-center">
            <p className="text-lg text-gray-400 mb-8">Get Vincify now on the App Store or Google Play Store</p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                <StoreButton icon={<AppleIcon />} storeName="App Store" />
                <StoreButton icon={<PlayStoreIcon />} storeName="Google Play" />
            </div>
          </section>

        </main>

        <footer className="border-t border-white/10 py-8">
          <div className="container mx-auto px-6 flex flex-col md:flex-row justify-between items-center text-gray-400 gap-6">
            <div className="text-sm">
              &copy; 2025 Vincify. All rights reserved.
            </div>
            <div className="order-first md:order-none">
              <a href="#" onClick={(e) => { e.preventDefault(); setPage('support'); }} className="hover:text-white transition-all duration-300 text-sm hover:-translate-y-px">Support</a>
            </div>
            <div className="flex items-center gap-x-6 text-sm">
              <a href="https://drive.google.com/file/d/1yccqaCRiK598Ggx2U_C9Tbj8xqb8B6Cy/view" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-all duration-300 hover:-translate-y-px">Privacy Policy</a>
              <a href="https://drive.google.com/file/d/1w53iau9GvUW5EzOQgzabCyeXgwUyRc6_/view" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-all duration-300 hover:-translate-y-px">Terms & Conditions</a>
              <a href="https://drive.google.com/file/d/1TMCdK2iczd_jlzD2NFkfN_Xzy55c1xro/view" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-all duration-300 hover:-translate-y-px">EULA</a>
            </div>
          </div>
        </footer>
    </>
  );
};


const SupportPage: React.FC<{ setPage: (page: string) => void }> = ({ setPage }) => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [status, setStatus] = useState<'idle' | 'submitting' | 'success' | 'error'>('idle');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (status === 'submitting') return;

    if (!name.trim() || !email.trim() || !message.trim()) {
      alert("Please fill in all fields.");
      return;
    }

    setStatus('submitting');
    
    // This is a simulation. In a real application, you would make a fetch request
    // to your backend or a form service like Formspree.
    
    // Example for a real backend:
    /*
    try {
      const response = await fetch('YOUR_BACKEND_ENDPOINT_HERE', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name, email, message })
      });

      if (response.ok) {
        setStatus('success');
      } else {
        setStatus('error');
      }
    } catch (error) {
      console.error('Submission failed:', error);
      setStatus('error');
    }
    */
    
    // Simulation logic:
    setTimeout(() => {
        // Simulate a successful submission
        setStatus('success');

        // To simulate an error, you could uncomment the next line
        // setStatus('error');
    }, 1500);
  };
  

  return (
    <div className="min-h-screen flex flex-col">
      <header className="py-6 container mx-auto px-6">
        <div className="flex justify-start">
            <a href="#" onClick={(e) => { e.preventDefault(); setPage('main'); }} className="cursor-pointer transition-transform hover:scale-105">
                <VincifyLogo />
            </a>
        </div>
      </header>
      <main className="flex-grow flex items-center justify-center">
        <div className="w-full max-w-2xl mx-auto px-6 py-12 md:py-20">
            <div className="text-center mb-12">
                <h2 className="text-4xl md:text-5xl font-bold text-white">Contact Support</h2>
                <p className="text-lg text-gray-400 mt-4">We're here to help. Fill out the form below and we'll get back to you as soon as possible.</p>
            </div>
            
            <div className="bg-white/5 p-8 rounded-2xl border border-white/10">
              {status === 'success' ? (
                <div className="text-center py-10">
                  <h3 className="text-2xl font-bold text-white mb-2">Thank You!</h3>
                  <p className="text-gray-300">Your message has been sent. We'll get back to you shortly.</p>
                </div>
              ) : (
                <form onSubmit={handleSubmit} className="space-y-6">
                    <div>
                        <label htmlFor="name" className="block text-sm font-medium text-gray-300 mb-2">Name</label>
                        <input
                            type="text"
                            id="name"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            required
                            className="w-full bg-white/5 border border-white/10 rounded-lg py-3 px-4 text-white placeholder-gray-500 focus:ring-2 focus:ring-purple-500 focus:outline-none transition-all"
                            placeholder="Your Name"
                            aria-label="Name"
                        />
                    </div>
                    <div>
                        <label htmlFor="email" className="block text-sm font-medium text-gray-300 mb-2">Email</label>
                        <input
                            type="email"
                            id="email"
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            required
                            className="w-full bg-white/5 border border-white/10 rounded-lg py-3 px-4 text-white placeholder-gray-500 focus:ring-2 focus:ring-purple-500 focus:outline-none transition-all"
                            placeholder="you@example.com"
                            aria-label="Email Address"
                        />
                    </div>
                    <div>
                        <label htmlFor="message" className="block text-sm font-medium text-gray-300 mb-2">Message</label>
                        <textarea
                            id="message"
                            value={message}
                            onChange={(e) => setMessage(e.target.value)}
                            required
                            rows={6}
                            className="w-full bg-white/5 border border-white/10 rounded-lg py-3 px-4 text-white placeholder-gray-500 focus:ring-2 focus:ring-purple-500 focus:outline-none transition-all"
                            placeholder="How can we help you?"
                            aria-label="Your Message"
                        ></textarea>
                    </div>
                    <div>
                        <button
                            type="submit"
                            disabled={status === 'submitting'}
                            className="w-full bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 text-white font-bold py-3 px-6 rounded-lg transition-all duration-300 transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-950 focus:ring-purple-500 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            {status === 'submitting' ? 'Submitting...' : 'Submit'}
                        </button>
                    </div>
                     {status === 'error' && (
                        <p className="text-center text-red-400 text-sm">
                            Something went wrong. Please try again.
                        </p>
                    )}
                </form>
              )}
            </div>
        </div>
      </main>
      <footer className="border-t border-white/10 py-8 mt-auto">
          <div className="container mx-auto px-6 flex flex-col md:flex-row justify-between items-center text-gray-400 gap-6">
            <div className="text-sm">
              &copy; 2025 Vincify. All rights reserved.
            </div>
            <div className="flex items-center gap-x-6 text-sm">
              <a href="https://drive.google.com/file/d/1yccqaCRiK598Ggx2U_C9Tbj8xqb8B6Cy/view" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-all duration-300 hover:-translate-y-px">Privacy Policy</a>
              <a href="https://drive.google.com/file/d/1w53iau9GvUW5EzOQgzabCyeXgwUyRc6_/view" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-all duration-300 hover:-translate-y-px">Terms & Conditions</a>
              <a href="https://drive.google.com/file/d/1TMCdK2iczd_jlzD2NFkfN_Xzy55c1xro/view" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-all duration-300 hover:-translate-y-px">EULA</a>
            </div>
          </div>
        </footer>
    </div>
  );
};


const App: React.FC = () => {
  const [page, setPage] = useState('main'); // 'main' or 'support'

  return (
    <div className="bg-gray-950 text-gray-200 antialiased">
        <div className="relative overflow-hidden">
            <div className="absolute top-0 left-0 -z-10 w-full h-full pointer-events-none">
                <div className="absolute top-[-20%] left-[-20%] w-[500px] h-[500px] bg-gradient-radial from-purple-600/30 to-transparent blur-3xl rounded-full"></div>
                <div className="absolute bottom-[-20%] right-[-20%] w-[500px] h-[500px] bg-gradient-radial from-indigo-600/30 to-transparent blur-3xl rounded-full"></div>
            </div>
            {page === 'main' ? <MainPage setPage={setPage} /> : <SupportPage setPage={setPage} />}
        </div>
    </div>
  );
};

export default App;